### ISSUE TITLE
Game Setup

### ISSUE THREAD

**Issue by Onkar627** [Akhil-Sharma30/AI-BASED-2-PLAYER-GAME#7]
Need to make first the board of size 4x4 and start only with knights.

**Comment by parthxtripathi** [comment]
@Onkar627 @Akhil-Sharma30  I would like to setup the game environment.

**Comment by Akhil-Sharma30** [comment]
> @Onkar627 @Akhil-Sharma30 I would like to setup the game environment.

Yes, Sure try implementing a scene for a 4x4 to 8x8.

**Comment by Onkar627** [comment]
And also start with keeping only 2 knight pieces at corners on the 4x4 board @parthxtripathi .
